export default {
  "login": "Bhoomika015",
  "id": 55837162,
  "node_id": "MDQ6VXNlcjU1ODM3MTYy",
  "avatar_url": "https://avatars3.githubusercontent.com/u/55837162?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Bhoomika015",
  "html_url": "https://github.com/Bhoomika015",
  "followers_url": "https://api.github.com/users/Bhoomika015/followers",
  "following_url": "https://api.github.com/users/Bhoomika015/following{/other_user}",
  "gists_url": "https://api.github.com/users/Bhoomika015/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Bhoomika015/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Bhoomika015/subscriptions",
  "organizations_url": "https://api.github.com/users/Bhoomika015/orgs",
  "repos_url": "https://api.github.com/users/Bhoomika015/repos",
  "events_url": "https://api.github.com/users/Bhoomika015/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Bhoomika015/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Bhoomika S",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 12,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2019-09-26T11:05:04Z",
  "updated_at": "2020-10-27T09:28:40Z"
};
